# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            LetsHack
tagline:          'Hacking adventures with the Raspberry Pi, Arduino, ESP...etc.'
description:      'Hacking adventures with the Raspberry Pi, Arduino, ESP, etc.'
url:              https://tangowhisky37.github.io
baseurl:          /LetsHack

author:
  name:           'Trevor Warren'
  url:            https://twitter.com/tangowhisky37

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tangowhisky37


---
  layout:         page
  title:          About
  title:          HowTos
  title:          JustCode
---
