# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            RasPiSetupGuide
tagline:          'Hacking adventures with the Raspberry Pi, Arduino, ESP...etc.'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://tangowhisky37.github.io/RasPiSetupGuide/
baseurl:          /

author:
  name:           'Trevor Warren'
  url:            https://twitter.com/tangowhisky37

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tangowhisky37
